# Project information
site_name: 'Helios4 Wiki'
site_description: 'Helios4 Wiki'
site_author: 'Kobol Team'
site_url: 'https://wiki.kobol.io'

# Repository
repo_name: 'Helios4 GitHub Repo'
repo_url: 'https://github.com/helios-4'
edit_uri: ''

# Copyright
copyright: 'Copyright &copy; Kobol Innovations Pte. Ltd. 2019'

# Documentation and theme
theme:
  name: 'material'
  language: 'en'
  favicon: './img/favicon.png'
  logo: './img/helios4_logo.png'
  custom_dir: 'theme'
  palette:
    primary: 'teal'
    accent: 'pink'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'


# Options
extra:
  social:
    - type: 'home'
      link: 'https://kobol.io/helios4'
    - type: 'github'
      link: 'https://github.com/helios-4'
    - type: 'facebook'
      link: 'https://facebook.com/kobol.io'
    - type: 'twitter'
      link: 'https://twitter.com/kobol_io'
    - type: 'rss-square'
      link: 'https://blog.kobol.io'
  sd_release:
    latest: '31/07/2019'

# Google Analytics
google_analytics:
  - 'UA-96982596-2'
  - 'auto'

# Plugins
plugins:
  - search
  - git-revision-date

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: False
  - toc:
      permalink: True
  - lightgallery

# Page naming
nav:
- Introduction: 'index.md'
- Kit Assembly: 'kit.md'
- Download: 'download.md'
- Install: 'install.md'
- O/S:
  - Arch Linux : 'arch.md'
  - Armbian : 'armbian.md'
  - FreeBSD : 'freebsd.md'
  - Syncloud : 'syncloud.md'
  - U-Boot (bootloader) : 'uboot.md'
- Software:
  - Mdadm (RAID) : 'mdadm.md'
  - NextCloud : 'nextcloud.md'
  - OpenMediaVault : 'omv.md'
- Hardware:
  - Overview : 'hardware.md'
  - CESA (HW Crypto) : 'cesa.md'
  - GPIO : 'gpio.md'
  - I2C (OLED) : 'i2c.md'
  - LED : 'led.md'
  - PWM (Fan) : 'pwm.md'
  - SDIO (SD Card) : 'sdcard.md'
  - SPI (NOR Flash) : 'spi.md'
  - Wake-on-LAN : 'wol.md'
- Documents: 'docs.md'
- About: 'about.md'
